name: VueJS/Symfony app
on: [push]
jobs:
  backend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: phpunit, composer
          extensions: zip
      - name: Install dependancies
        run: composer install
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite
      - name: Prepare database to test
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          php bin/console --env=test doctrine:database:create
          php bin/console --env=test doctrine:schema:create
          php bin/console --env=test -n doctrine:fixtures:load
          php bin/phpunit tests/Controller/RecipeControllerTest.php
  backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:symfony_app
          context: .
          build-args: |
            DB_APP_SECRET=${{ secrets.DB_APP_SECRET }}
            DB_URL=${{ secrets.DB_URL }}
            DB_MESSENGER=${{ secrets.DB_MESSENGER }}
      - name: Build and push nginx proxy
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:symfony_nginx
          context: ./nginx
  frontend-check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:unit
  frontend-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:vue_app
          context: ./frontend