name: VueJS/Symfony app
on: [push]
jobs:
  backend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: phpunit, composer
          extensions: zip
      - name: Install dependancies
        run: composer install
      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite
      - name: Prepare database to test
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
        run: |
          php bin/console --env=test doctrine:database:create
          php bin/console --env=test doctrine:schema:create
          php bin/console --env=test -n doctrine:fixtures:load
          php bin/phpunit tests/Controller/RecipeControllerTest.php
  frontend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        